# vault_clear.yml:
#   - has vars pointing to matching encrypted vars in vault_enc.yml
#
# vault_enc.yml:
#   - orig encrypt:   ansible-vault encrypt host_vars/vault_enc.yml
#   - edit in place:  ansible-vault edit host_vars/vault_enc.yml
#   - view read-only: ansible-vault view host_vars/vault_enc.yml
#
# Notes:
#   - ansible-vault cmd uses vault password from vault_password.txt
#   - ansible-playbook cmd also uses vault password from vault_password.txt
#   - ansible.cfg wires up vault_password.txt
#   - playbook.yml wires up linking in vars from vault_enc.yml, vault_clear.yml

# Tailscale auth key
vault_clear_tailscale_auth_key: "{{ vault_enc_tailscale_auth_key }}"

